language: node_js
dist: trusty
sudo: required

node_js:
  - '8'
  - '10'

services:
  - docker

install:
  - yarn install

script:
  - yarn lint
  - yarn lint:test
  - docker-compose pull
  - yarn test
